# Generated by Django 3.0 on 2019-12-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Unique_Squirrel_ID', models.CharField(help_text='Squirrel ID', max_length=30)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('Date', models.DateField(help_text='Date of the sighting')),
                ('Age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('', ''), ('?', '?')], help_text='Age', max_length=50)),
                ('Location', models.CharField(choices=[('ground plane', ' Ground Plane'), ('above ground', 'Above Ground'), ('other', 'Other')], default='other', help_text='Location of the Squirrel', max_length=100)),
                ('Specific_location', models.CharField(help_text='Particular Location of the sighting', max_length=30)),
                ('Primary_Fur_Colour', models.CharField(choices=[('black', 'Black'), ('cinnamon', 'Cinnamon'), ('gray', 'Gray')], help_text='Color of the squirrel fur', max_length=20)),
                ('Running', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Is it on the run?', max_length=20)),
                ('Chasing', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Is it chasing something?', max_length=20)),
                ('Climbing', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Is it climbing something?', max_length=20)),
                ('Eating', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Is it eating something?', max_length=20)),
                ('Foraging', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Is it looking for food?', max_length=20)),
                ('Other_Activities', models.CharField(help_text='What else is it doing?', max_length=100)),
                ('Kuks', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Is it making short noise?', max_length=20)),
                ('Quaas', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Is it making longer noises?', max_length=20)),
                ('Moans', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Is it moaning?', max_length=20)),
                ('Tail_flags', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Is it flagging it’s tail?', max_length=20)),
                ('Tail_twitches', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Is it twitching it’s tail?', max_length=20)),
                ('Approaches', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Is it approaching?', max_length=20)),
                ('Indifferent', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Is it indifferent?', max_length=20)),
                ('Runs_from', models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Is it running away?', max_length=20)),
            ],
        ),
    ]
