# Generated by Django 3.0 on 2019-12-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrels',
            name='Latitude',
            field=models.FloatField(help_text='Latitude'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Longitude',
            field=models.FloatField(help_text='Longitude'),
        ),
    ]
