# Generated by Django 3.0 on 2019-12-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelapp', '0002_auto_20191209_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrels',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Squirrel ID', max_length=30, primary_key=True, serialize=False),
        ),
    ]
